# Generated by Django 3.2.5 on 2022-08-23 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cuenta',
            table='cuenta',
        ),
    ]
