# Generated by Django 3.2.5 on 2022-08-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.TextField()),
                ('customer_surname', models.TextField()),
                ('customer_dni', models.TextField(db_column='customer_DNI')),
                ('customer_type', models.CharField(max_length=9)),
                ('dob', models.TextField(blank=True, null=True)),
                ('branch_id', models.IntegerField()),
                ('img_profile', models.ImageField(upload_to="{'{customer_dni}'}")),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
    ]
